{% set name = "prmon" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/HSF/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 26d628a45c577d2bffb4cc7e11e940d0229ef9a5fe6617abd51a60486132ec8d
  folder: source

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - nlohmann_json
    - spdlog
    - fmt

test:
  commands:
    - prmon --help
    - prmon --json-summary test.json -- sleep 5
    - cat test.json

about:
  home: https://github.com/HSF/prmon/
  license: Apache-2.0
  license_file: source/LICENSE
  summary: Process Monitor (prmon)
  description: |
    The PRocess MONitor is a small stand alone program that can monitor the
    resource consumption of a process and its children. This is useful in the
    context of the WLCG/HSF working group to evaluate the costs and performance
    of HEP workflows in WLCG. In a previous incarnation (MemoryMonitor) it has
    been used by ATLAS for sometime to gather data on resource consumption by
    production jobs. One of its most useful features is to use smaps to
    correctly calculate the Proportional Set Size in the group of processes
    monitored, which is a much better indication of the true memory consumption
    of a group of processes where children share many pages.
  doc_url: https://github.com/HSF/prmon/#running
  dev_url: https://github.com/HSF/prmon/

extra:
  recipe-maintainers:
    - chrisburr
